-- Trap handler for IBM Director.
-- If you want to enable alias mapping, set "useAliasMapping" to "true".
-- See https://kb.op5.com/x/r4Gx for more information!

local useAliasMapping = false

local trapType              = trap[[.1.3.6.1.4.1.2.6.159.202.1]]
local trapSeverity          = trap[[.1.3.6.1.4.1.2.6.159.202.2]]
local trapSenderName        = trap[[.1.3.6.1.4.1.2.6.159.202.3]]
local trapManagedObjectName = trap[[.1.3.6.1.4.1.2.6.159.202.4]]
local trapText              = trap[[.1.3.6.1.4.1.2.6.159.202.5]]
local trapCategory          = trap[[.1.3.6.1.4.1.2.6.159.202.6]]


-- Function to match "ManagedObjectName" against a host or alias in Monitor.
-- Requires the "alias-mapping" module, generated by the "gen-mapping.lua" script.
function map(name)

	for i, v in ipairs(mapping) do
		if v[name] then
			return v[name]
		else
			local name2 = string.match(name, "^([%w-]+)%.[%w-]+%.[%w-]+")
			if name2 and v[name2] then
				return v[name2]
			end
		end
	end
	return nil
end


-- Checks if alias mapping should be enabled or not
if useAliasMapping == true then
	log("useAliasMapping is true - using map function to set host")
	include "alias-mapping"
	result.host = map(trapManagedObjectName) or "IBM-Director"
else
	log("useAliasMapping is false - using trap field to set host")
	result.host = trapManagedObjectName
end

result.service = "IBM-Director"
result.tag     = trapManagedObjectName .. "/" .. trap.oid
result.message = trapManagedObjectName .. ": " .. trapText

log(trapManagedObjectName .. " mapped to " .. result.host)


if trapCategory == "Resolution" then
	result.state = STATE.OK
else
	if trapSeverity == "Informational" then
		result.state = STATE.OK
	elseif trapSeverity == "Minor" then
		result.state = STATE.OK
	elseif trapSeverity == "Warning" then
		result.state = STATE.WARNING
	elseif trapSeverity == "Alert" then
		result.state = STATE.CRITICAL
	elseif trapSeverity == "Critical" then
		result.state = STATE.CRITICAL
	elseif trapSeverity == "Fatal" then
		result.state = STATE.CRITICAL
	end
end
